"""empty message

Revision ID: f4232e1d6d1a
Revises: 6d25d2455a52
Create Date: 2018-12-05 11:04:18.549743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4232e1d6d1a'
down_revision = '6d25d2455a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Search')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Search',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Search_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Search_pkey')
    )
    # ### end Alembic commands ###
